name: test CNN
on:
    workflow_call: 


jobs:
    test-CNN:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@4

            - name: Run test
              run: |
                  echo "Starting the CNN Test"
                  echo trained_xor_model.txt | ./build/BUILD_CNN_FROM_SCRATCH

              
              
